### ISSUE TITLE
Demo exploiting all these vulnerabilities

### ISSUE THREAD

**Issue by tomalex0** [helmetjs/helmet#105]
Do you have any demo app which have all these vulnerabilities . Just want to try out `helmet` in that and figure out how its working. If you have any reference  also that would be great.

**Comment by EvanHahn** [comment]
This is a good idea. We don't have a demo app, though.

Does anyone want to take this on?

**Comment by kaushik94** [comment]
@EvanHahn This is a great tool. Sorry for commenting since I felt this is only a small question. How do we use helmet or disable it when working locally. For example I am implementing a share button and it makes a request to https://cdn.api.twitter.com/ but helmet blocks. I don't want to frequently change the helmet configuration since it might screw things up if I don't revert back. Is there a way to work with this on local ?

**Comment by EvanHahn** [comment]
@kaushik94 Let's open a new issue and discuss it there. I opened #107.

**Comment by EvanHahn** [comment]
@tomalex0 If you (or anyone) would like to send a demo app (even if it's incomplete), we can add it to the project. I do not have time to implement this on my own.

**Comment by maasencioh** [comment]
Hi @EvanHahn, I will like to help, but the idea will be to make an app with all the vulnerabilities or a project for each vulnerability?

**Comment by evilpacket** [comment]
The goal is to make it as simple as possible so that devs can understand by example why it's bad.

Writing good, bad / exploitable code can be difficult as most examples are contrived. I think either approach is valid as long as they are easy to maintain and simple to understand. 


Adam

**Comment by EvanHahn** [comment]
I'm going to close this issue because (1) there hasn't been movement on it in months (2) [our docs](https://helmetjs.github.io/docs/) hopefully cover a lot of this need. I don't think this is ever going to get done, unfortunately.
