### ISSUE TITLE
setAllHeaders to false still include X-Content-Security-Policy and X-WebKit-CSP

### ISSUE THREAD

**Issue by mech** [helmetjs/helmet#110]
The `setAllHeaders: false` supposed to only set one header and that is `Content-Security-Policy`, but I am seeing the other 2 headers also.

My config:

```js
app.use(helmet.csp({
  directives: {
    defaultSrc: ["'self'"],
    scriptSrc: ["'self'"],
    styleSrc: [],
    objectSrc: []
  },

  setAllHeaders: false
}));
```

**Comment by EvanHahn** [comment]
Investigating now.

**Comment by EvanHahn** [comment]
I investigated this and found another small bug (whoops!) but I'm not sure this is a bug.

- If `setAllHeaders` is `true`, Helmet will _always_ set 3 headers, no matter what: `Content-Security-Policy`, `X-Content-Security-Policy`, and `X-WebKit-CSP`.
- If `setAllHeaders` is `false`, Helmet will look at the `user-agent` and decide which of the three headers to set. If the `user-agent` is unrecognized, it will set all 3 headers because it's not sure.

It might be that you have `setAllHeaders` set to `false` but are throwing an unknown browser at Helmet. Is this possible?

Does this match your understanding? I may want to update the documentation to better reflect this.

**Comment by EvanHahn** [comment]
@mech Any updates?

**Comment by mech** [comment]
Ya I was using httpie to request instead of a browser. I guess that why I see all 3 of it. Closing this and tks for clarifying :)

**Comment by webuniverseio** [comment]
Leaving this comment because it might be useful for someone.
This turned out to be an issue for me because our mobile app has custom user agent and as a result helmet was setting 3 headers instead of one (understandable behavior for compatibility). CSP header was pretty large and when it was duplicated 3 times it caused Akamai (CDN provider) to return 502. I fixed that by checking my custom header after helmet middleware and removing unnecessary legacy CSP headers.
