### ISSUE TITLE
Fully integrate dns-prefetch-control

### ISSUE THREAD

**Issue by EvanHahn** [helmetjs/helmet#111]
https://github.com/helmetjs/dns-prefetch-control

**Comment by Lionad-Morotar** [comment]
Hi，I wander what kind of security issues does DNS-Prefetch-Control policy related to...

**Comment by EvanHahn** [comment]
@Lionad-Morotar It mostly exists as a privacy benefit to users. Does that help?

**Comment by Lionad-Morotar** [comment]
Hi，感谢回应。

我在 MDN 中找到一些关于 DNS prefetch 的描述：https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-DNS-Prefetch-Control

它提到：“打开 DNS prefetch 之后，在图片数量较多的页面，能带来至少 5% 的加载速度提升”，但并没有涉及到安全问题。
您能举个例子，详细解释一下因 DNS prefetch 导致用户隐私问题出现的原因或场景吗？

---

Hi, thanks for reply.

I found some descriptions of DNS prefetch in MDN. It mentions that "after opening DNS prefetch, the page loading speed can be increased by 5%", but it does not involve security issues or the description of "user privacy benefit".

Can you give an example to explain in detail the reasons or scenarios of user privacy problems caused by DNS prefetch?

**Comment by EvanHahn** [comment]
DNS prefetching gives information to the DNS resolver which it could use to learn more about your browsing.

For example, let's say that you perform a search on DuckDuckGo for "grapes". Without DNS prefetching, your DNS resolver will know that you wanted to fetch `duckduckgo.com`, but not _what_ you searched. With DNS prefetching, it will see that you wanted `duckduckgo.com` and then several sites shortly after. The resolver could use this extra information to guess that you searched for "grapes".

[This paper](https://www.usenix.org/legacy/events/leet10/tech/full_papers/Krishnan.pdf) seems to offer more detail, though I have only skimmed it.
