### ISSUE TITLE
Passing configuration

### ISSUE THREAD

**Issue by julien-f** [helmetjs/helmet#112]
It could be nice if there could be a way to pass configuration to the middleware directly from the high level collection (which I like to use because I trust it is a much more sensible pick that I would have done myself).

```js
app.use(helmet({
  hsts: {
    maxAge: 1000 * 60 * 60 * 24 * 365
  }
}))
```

**Comment by EvanHahn** [comment]
This is something that Helmet used to have but I removed it because I'd like you to either (1) use the defaults (2) customize each piece; not something in between. That cuts down on the amount of maintenance I'd have to do, and I prefer to have only one way to do things.

Is this much worse than using each middleware by itself?

**Comment by julien-f** [comment]
I agree with you that the user should either use the defaults or customize each piece, unfortunately, as as been said in helmetjs/hsts#5, it's not always easy to know what the defaults should be.

IMHO, without configuration, this package should provide what it aims to do, provide the maximum security possible.

**Comment by EvanHahn** [comment]
The Helmet defaults should make you more secure without breaking your existing app. For maximum security, you should use and customize the individual pieces.

That's been my philosophy, anyway. Some of the most important features of this library require customization (CSP, HSTS, etc) and so we can't include them in the default.

Does that make sense? I could be convinced otherwise, but I'd rather not break existing apps with the default settings.

**Comment by grtjn** [comment]
I think it makes sense to have this global config. Most people will be interested in starting off with the defaults, and might just want to enable one extra item, or override the default options for just one of the default guards. I'd rather not have to list out all items individually just because I want to override xssFilter option for instance..

Ideally I would like to be able to do something like:

```js
app.use(helmet({
  csp: { // enable and configure
    directives: {
      defaultSrc: ["'self'"]
    },
    setAllHeaders: true
  },
  dnsPrefetchControl: true, // just enable, with whatever defaults
  xssFilter: { // enabled by default, but override defaults
    setOnOldIE: true
  },
  noCache: false // make sure it is disabled
}))
```

..and be sure new default guards will be enabled automatically at upgrade..

**Comment by julien-f** [comment]
@grtjn Thanks for explaining my concern in a much better way that I could have done :)

**Comment by EvanHahn** [comment]
This makes sense to me.

Would either of you like to submit a PR I can take a look at?

**Comment by siboulet** [comment]
+1

Due to the "permissive" defaults of the HSTS module (discussed here https://github.com/helmetjs/hsts/issues/5), it be great to just be able to override the HSTS config and keep everything else to default like this:


```
app.use(helmet({
  hsts: {
    maxAge: 1000 * 60 * 60 * 24 * 365,
    includeSubDomains: true,
  }
}))
```

**Comment by EvanHahn** [comment]
This is now in `helmet@2.0.0`.

**Comment by julien-f** [comment]
Thank you :)
