### ISSUE TITLE
Does it work for React?

### ISSUE THREAD

**Issue by FlyRocketDrones** [helmetjs/helmet#211]
Does Helmet work for React? If so, how can I set it up?

**Comment by EvanHahn** [comment]
Helmet is a Node library for Express (and Express-like) servers, and it shouldn't meaningfully affect the way you use React. This module has no meaningful integrations with React.

You may be looking for [React Helmet](https://github.com/nfl/react-helmet), a module that lets you manipulate the `<head>` of your document.

I'm going to close this issue because I think I've answered your question, but let me know if you need more information.

**Comment by FlyRocketDrones** [comment]
Helmet adds useful security procedures like contentSecurityPolicy so my intention was to use Helmet with my React.

**Comment by EvanHahn** [comment]
By default, Helmet doesn't add a Content Security Policy, though that's one of its features. It's hard to give general advice about how to use a Content Security Policy with React, but you'll want to make sure you've allowed any JavaScript in the `script-src` directive.

Are you running into any trouble with that?

**Comment by FlyRocketDrones** [comment]
Well, no. I found: https://tomssl.com/2016/06/30/how-to-fix-the-http-response-headers-on-azure-web-apps-to-get-an-a-plus-on-securityheaders-io/

That added all necessary securityheaders. Though, I was thinking, instead of using that I could use helmet with my app to take care of all of that...

**Comment by EvanHahn** [comment]
Helmet adds various HTTP response headers. You don't need Helmet to set those, but Helmet certainly can do it.

Does that help?

**Comment by FlyRocketDrones** [comment]
Yes, thank you! I will check script-src directive : )
