### ISSUE TITLE
Fix npm scripts on Windows

### ISSUE THREAD

**Issue by EvanHahn** [helmetjs/helmet#227]
Some of the npm scripts won't work on Windows. We should fix that.

**Comment by EvanHahn** [comment]
Addressed in a4e02c56df299b31154b07a1c9553bfe6defe378.

**Comment by XhmikosR** [comment]
@EvanHahn FYI there are a few more Windows npm script issues:

1. `rm` isn't available on Windows. You could use rimraf or another small cross-platform package
2. `./bin/build-middleware-package.js` can't work because shebangs don't work on Windows; use `node ./bin/build-middleware-package.js` instead

**Comment by EvanHahn** [comment]
@XhmikosR Thanks for letting me know.

Would you like to open pull requests for these? (I'd prefer this as two small PRs instead of one big one, if possible.)

If not, I can get around to it.

**Comment by XhmikosR** [comment]
I can take a stab at it in the next days. Would you be interested in switching to GitHub Actions and test Windows too?

**Comment by EvanHahn** [comment]
Not yet—let's keep things on Travis for now.

**Comment by EvanHahn** [comment]
I'll plan to fix this sometime next week (the week of 2020-09-14) unless I get a PR before then.
