### ISSUE TITLE
Issues with TypeScript imports in 4.0.0

### ISSUE THREAD

**Issue by zen0wu** [helmetjs/helmet#235]
Code like below overrides the exported object, which causes `default` being missing from every module.

```
module.exports = contentSecurityPolicy;
export default contentSecurityPolicy;
```

For example, inside `index.ts`, add `console.log("wat", expectCt);` under the import, and we'll see it's `undefined`.

**Comment by EvanHahn** [comment]
What does your build setup look like? I didn't experience this problem when testing things, but I may have made a mistake.

Also: are you using `helmet` or `helmet-csp`?

**Comment by zen0wu** [comment]
I'm using `helmet`.

I believe this issue is universal. For example, create a `test.ts` in the root with
```ts
import helmet from './index'

console.log(helmet)
```

It outputs `undefined`.

**Comment by EvanHahn** [comment]
A couple of questions to help me debug:

1. What does your `tsconfig.json` look like? Specifically, what is the value of `esModuleInterop`?
2. Do you still have `@types/helmet` installed?

**Comment by Hongbo-Miao** [comment]
Seems like a TypeScript config issue.

I just upgrades to helmet 4.0.0, the code is at https://github.com/Hongbo-Miao/hongbomiao.com/blob/master/server/src/middlewares/helmet.middleware.ts
tsconfig.json is at https://github.com/Hongbo-Miao/hongbomiao.com/blob/master/server/tsconfig.json

Hopefully it helps.

**Comment by anthony-telljohann** [comment]
I was able to resolve this by ignoring typescript errors before using `helmet`

```typescript
import * as helmet from 'helmet'
...
// @ts-ignore
app.use(helmet(helmetConfig))
```

I believe this is because the default `helmet` export has an incorrectly defined type.

**Comment by EvanHahn** [comment]
I'd like to fix the Helmet types.

Helmet is a CommonJS module (in other words, it uses `module.exports` and not `export ...`). Therefore, without `esModuleInterop`, I would expect users to do something like this:

```typescript
import helmet = require("helmet");
```

With `esModuleInterop`, I'd expect something like this to work:

```typescript
import helmet from "helmet";
```

I'm not an expert at how TypeScript modules work, nor am I certain why some people are having problems and some are not.

If anyone has suggestions for how to fix this, I'd appreciate it!

**Comment by tobeno** [comment]
To my understanding you would need to export helmet using `export = helmet` (similar to what was done in the old 3.x.x typings in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/helmet/index.d.ts) in your index.ts file. This would replace both the default export and the module.exports. Otherwise `import helmet = require('helmet')` (or `import * as helmet from 'helmet'`) will not work as the TypeScript compiler thinks there is only a default export.

This seems to be the correct way to handle CommonJS style exports in TypeScript: https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require

As far as I understand the concept, this should also still work correctly if importing projects use esModuleInterop=true. So hopefully not a breaking change.

In the future it could be interesting to move away from exporting the function directly and use a named export instead (so import { helmet } from 'helmet' and const { helmet } = require('helmet'); ). 

As an alternative you could also look into creating a separate ESM build with a proper default export. But that would of course break existing `import * as helmet from 'helmet'`. So in any case a breaking change would be needed for either solution.

Think for now sticking with pure CommonJS seems to be the best bet.

**Comment by sehrope** [comment]
+1 for named exports. They play nice with editor auto completion as well.

**Comment by EvanHahn** [comment]
Is there a way to do `export = helmet` and still export the types, such as `HelmetOptions`? I think the answer is "no".

**Comment by thepostmillennial** [comment]
I got the same issue when I upgrade the helmet from **3.23.3** to **4.0** in my NestJS typescript project. any idea how to resolve this issue?

**Comment by thepostmillennial** [comment]
here is the working solution:

>import * as helmet from 'helmet'

>async function bootstrap() {
>  const app = await NestFactory.create(AppModule)
`  app.use(helmet) //  app.use(helmet()) =>  app.use(helmet)`
> }

**Comment by zen0wu** [comment]
re named exports - They're generally a good idea IMO. Since this is a major version, it's a good reason to justify the change to named exports?

**Comment by EvanHahn** [comment]
This should be fixed in the next version. Please try it out with `npm install helmet@4.1.0-rc.2` and let me know what you think. Once I get a few successful reports, I'll release it.

**Comment by razorness** [comment]
```typescript
import helmet = require('helmet');

// ...

app.use(helmet());
```

Tested with TypeScript `v3.9.7` and NestJS:
```
$ nest info

 _   _             _      ___  _____  _____  _     _____
| \ | |           | |    |_  |/  ___|/  __ \| |   |_   _|
|  \| |  ___  ___ | |_     | |\ `--. | /  \/| |     | |
| . ` | / _ \/ __|| __|    | | `--. \| |    | |     | |
| |\  ||  __/\__ \| |_ /\__/ //\__/ /| \__/\| |_____| |_
\_| \_/ \___||___/ \__|\____/ \____/  \____/\_____/\___/


[System Information]
OS Version     : Windows 10
NodeJS Version : v12.18.2
YARN Version    : 1.22.4

[Nest CLI]
Nest CLI Version : 7.4.1

[Nest Platform Information]
platform-express version : 7.0.0
passport version         : 7.1.0
typeorm version          : 7.1.0
common version           : 7.0.0
core version             : 7.0.0
```

Looks good to me. Thanks!

**Comment by czzonet** [comment]
First thing is make it work, optimizing the type export is the next. :)

**Comment by EvanHahn** [comment]
> First thing is make it work, optimizing the type export is the next. :)

@czzonet What do you mean?

**Comment by czzonet** [comment]
It is better if it can work like this? @EvanHahn 

```ts
import {helmet, HelmetOptions} from 'helmet'
```

**Comment by pietrzakadrian** [comment]
change the helmet version to this: ` "helmet": "4.1.0-rc.2",` in package.json

**Comment by EvanHahn** [comment]
@czzonet I don't think that's possible, unfortunately. It's arguably a breaking change, but it only affects TypeScript users where things weren't working well anyway.

@pietrzakadrian What do you mean? Is there something wrong with Helmet, or are those instructions for other Helmet users?

**Comment by anthony-telljohann** [comment]
@EvanHahn After installing `helmet@4.1.0-rc.2`, I was able to fix the typescript errors by importing the default export:
```ts
import helmet from 'helmet'
app.use(helmet(helmetConfig))
```

**Comment by sehrope** [comment]
+1 for helmet@4.1.0-rc.2. Typing issues are resolved.

For anybody that was previously importing the `HelmetOptions` interface, e.g. you're assigning the options to a variable rather than directly invoking the middleware function, you can do it by extracting the type from the middleware arg:

```typescript
import helmet = require('helmet');
const opts: Parameters<typeof helmet>[0] = {
    // strongly typed helmet options go here...
};
helmet(opts);
```

**Comment by EvanHahn** [comment]
Planning to release `helmet@4.1.0` soon.

**Comment by EvanHahn** [comment]
This has been fixed in `helmet@4.1.0`. Please let me know if you run into any issues!

**Comment by joshuajung** [comment]
Works like a charm. For everyone running into issues, make sure to remove any earlier installations of `@types/helmet`.

**Comment by jsaguet** [comment]
You can also use 
```typescript
import helmet from 'helmet';
app.use(helmet());
```
if you use `"allowSyntheticDefaultImports": true,` in your tsconfig.json
(works with TS 3.9.7)

**Comment by fox1t** [comment]
In order to have the same behavior as before we had to import that interface like this: https://github.com/fastify/fastify-helmet/blob/6637767c0b3d088e0f8cf0b440112df4c48f9566/index.d.ts

Said that I have to say that we had many problems with esModuleInterop in the fastify ecosystem, but we fixed all of them and now we support seamlessly TS, CJS and ESM, all with correct typings. Our solution was the "infamous triplet". 

You can read more about it [here](https://gist.github.com/fox1t/314e5fe9784ff7bb695b4603b97d978d) and [here](https://github.com/fox1t/modules-playground)

If you want to follow the same approach, I'll be happy to help you, if needed/wanted.
