### ISSUE TITLE
How to set nonce in helmet >4.0?

### ISSUE THREAD

**Issue by mercteil** [helmetjs/helmet#240]
In version 3 I could set nonce from `res.locals` like this:

```javascript
...
        scriptSrc: [
          (req, res) => `'nonce-${res.locals.nonce}'`,
          "'strict-dynamic'",
...
```

In 4.0 I get an error when providing a function for setting nonce:

`Error: Content-Security-Policy received an invalid directive value for "script-src"`

So the question is how to set nonce in helmet 4.0 ?

**Comment by mercteil** [comment]
.. apparently by picking and forwarding the context manually

```javascript
server.use((req, res, next) =>
    helmet.contentSecurityPolicy({
      directives: {
        ...
        scriptSrc: [
          `'nonce-${res.locals.nonce}'`,
          "'strict-dynamic'",
         ...
        ],
      },
    })(req, res, next)
```

**Comment by einfallstoll** [comment]
I don't like this. Also, this should have been mentioned in the changelog.

**Comment by EvanHahn** [comment]
@mercteil That's exactly right. Here's [a wiki page](https://github.com/helmetjs/helmet/wiki/Conditionally-using-middleware#i-want-to-use-some-middleware-with-different-options) describing how to do that in more detail.

@einfallstoll Good point. I've added it to the changelog in c01ad1e37c964df0108c37da4dd32af4630df95e.

This has made me realize that I need to create a migration guide. See #241 to track this.

I'm going to close this issue because I think this has been resolved, but if folks really want this feature, we can discuss adding it back.

**Comment by XhmikosR** [comment]
Agreed that this was pretty handy and simpler than the current solution. I haven't updated to helmet 4.0.0 due to this issue, so if it's not too much work, I'd like the ability to use functions back too 🙂

**Comment by EvanHahn** [comment]
This issue has been troublesome for a lot of people and I'm going to re-add the behavior to Helmet, likely in version 4.1.0. See #243 to follow my progress.

**Comment by EvanHahn** [comment]
This feature will be added to Helmet version 4.1.0. You can try it out today with `npm install helmet@4.1.0-rc.1`—let me know if it doesn't work for you, and follow along with the release at #245.
