### ISSUE TITLE
Add Helmet 4 migration guide

### ISSUE THREAD

**Issue by EvanHahn** [helmetjs/helmet#241]
Helmet 4 was recently released, and some people are having some trouble with it. (Nothing too major, I hope, but there were some breaking changes.)

I plan to create a migration guide for Helmet 4, which I'll track in this issue.

**Comment by trevordmillerwork** [comment]
This would be very helpful. On v3 we had `app.use(helmet())` and after upgrading to v4 get a console error of `Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy` and `Failed to load resource: An SSL error has occurred and a secure connection to the server cannot be made.` which I assume are related as no other breaking changes have been made.

**Comment by EvanHahn** [comment]
Made a first draft of this. See the [Helmet 4 upgrade guide](https://github.com/helmetjs/helmet/wiki/Helmet-4-upgrade-guide).

I'm going to close this issue for now, but will continue to make amendments to that page as new issues come in.
