### ISSUE TITLE
CSP Preventing page from loading "script-src" error

### ISSUE THREAD

**Issue by molaeiali** [helmetjs/helmet#249]
I'm loading a simple [apiDoc](https://apidocjs.com/) static page on express with helmet 4.1.0 and getting this error with csp enabled on helmet
```
Content Security Policy: Couldn’t process unknown directive ‘script-src-attr’
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”).
```
In version 3.22.1 of helmet it wasn't a problem.

Happy to provide any more info if needed, I don't know what I should mention more.

![Screenshot from 2020-08-16 22-45-39](https://user-images.githubusercontent.com/12999682/90341340-15ec5900-e014-11ea-90fd-f19ffd1a6017.png)

**Comment by EvanHahn** [comment]
My guess: this is happening because Helmet 4 has a Content Security Policy enabled by default. You have two options:

1. Set up a Content Security Policy for your site.
1. Disable the Content Security Policy.

Because it looks like you need to do dangerous things with `Function()`, I suspect it's okay to disable the CSP. You'd do that like this:

```js
app.use(helmet({
  contentSecurityPolicy: false,
}));
```

See [this section of the Helmet 4 upgrade guide](https://github.com/helmetjs/helmet/wiki/Helmet-4-upgrade-guide#there-is-now-a-default-policy) for more details.

I'm going to close this issue because I believe I've answered your question, but let me know if that's wrong and I can reopen.

**Comment by byF** [comment]
For anyone running into ` Content Security Policy: Couldn’t process unknown directive ‘script-src-attr’`, it might depend on your browser, Firefox (which I'm using) and Safari doesn't support it as of now (Aug 2021): https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src-attr#browser_compatibility
