### ISSUE TITLE
Unsafe-eval blocked by CSP in next/modules

### ISSUE THREAD

**Issue by sonu-sonam** [helmetjs/helmet#250]
When using helmet, I get this error in nextjs modules.
![Screen Shot 2020-08-17 at 3 19 17 pm](https://user-images.githubusercontent.com/23254380/90359768-21d02d80-e09d-11ea-86af-41443329987a.png)

Is there anything else need to be done besides setting up in expressjs?
![Screen Shot 2020-08-17 at 3 21 49 pm](https://user-images.githubusercontent.com/23254380/90359857-622fab80-e09d-11ea-93da-00decfcf0f3a.png)

How can I allow use of eval in those default modules?

**Comment by EvanHahn** [comment]
This is probably because Helmet 4 has a Content Security Policy enabled by default. You have two options:

1. Set up a Content Security Policy for your site.
1. Disable the Content Security Policy.

Disabling the CSP is the easiest, but is less secure. Do it like this:

```js
app.use(helmet({
  contentSecurityPolicy: false,
}));
```

See [this section of the Helmet 4 upgrade guide](https://github.com/helmetjs/helmet/wiki/Helmet-4-upgrade-guide#there-is-now-a-default-policy) for more details.

I'm going to close this issue because I believe I've answered your question, but let me know if that's wrong and I can reopen.
