### ISSUE TITLE
CSP policy not working properly 2.0

### ISSUE THREAD

**Issue by Branden77A** [helmetjs/helmet#261]
I've set the Content Security Policy like this: 

```
app.use(
  helmet.contentSecurityPolicy({
    directives: {
      defaultSrc: [
        "'self'",
        'https://*.mapbox.com',
        'https://*.stripe.com',
        'blob',
      ],
      baseUri: ["'self'"],
      fontSrc: ["'self'", 'https:', 'data:'],
      scriptSrc: ["'self'", 'https://*.cloudflare.com', "'unsafe-eval'"],
      imgSrc: ["'self'", 'https://www.gstatic.com', 'data'],
      scriptSrc: [
        "'self'",
        'https://*.stripe.com',
        'https://cdnjs.cloudflare.com',
        'https://api.mapbox.com',
        'https://js.stripe.com',
        'blob',
      ],
      frameSrc: ["'self'", 'https://*.stripe.com'],
      objectSrc: ["'none'"],
      styleSrc: ["'self'", 'https:', "'unsafe-inline'"],
      upgradeInsecureRequests: [],
    },
  })
);
```

and despite that I still get errors like this: 

`web_worker.js:9 Refused to create a worker from 'blob:http://127.0.0.1:8000/a115d817-1a59-46c1-97e5-355513ade597' because it violates the following Content Security Policy directive: "script-src 'self' https://*.stripe.com https://cdnjs.cloudflare.com https://api.mapbox.com https://js.stripe.com blob". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback. `

`Refused to load the image 'data:image/webp;base64,UklGRh4AAABXRUJQVlA4TBEAAAAvAQAAAAfQ//73v/+BiOh/AAA=' because it violates the following Content Security Policy directive: "img-src 'self' https://www.gstatic.com data".`

**Comment by BobbySpoon** [comment]
Also here I assume the problem arises from not probably configuring the CSP.  Data should be set as `"data:"` (note the colon). The same should also apply for `blob:`.
One good thing to do is to check in your browsers network tab if the headers u set are present. If they are, then the issue is most likely not with Helmet but from misconfiguration and/ or your browser not understanding/ supporting the set policy.
Remember that "all" that Helmet is doing is setting response headers, and they happen to follow specific/ strict rules. Although it does provide validation to your config input it doesn't do any sanitation.

**Comment by EvanHahn** [comment]
@Branden77A I believe @BobbySpoon is right. You should change `blob` to `blob:`.

I'm going to close this issue because I think that solves your problem, but let me know if that's wrong and I'll reopen.
