### ISSUE TITLE
Recommended headers for REST API?

### ISSUE THREAD

**Issue by LJNeon** [helmetjs/helmet#266]
I suspect several of these headers are unnecessary for a REST API that serves no web pages, but I'm not sure exactly which ones.

**Comment by EvanHahn** [comment]
Your suspicion is right.

It's worth keeping in mind that people can do strange things with iframes. For example: I recall an issue where JSON API responses could contain JavaScript, which would execute in Internet Explorer 11 if put in an iframe. So we started setting the `X-Frame-Options` header to mitigate that.

Let's go through the headers, one by one.

1. `Content-Security-Policy`: probably fine to omit, but might have some strange iframe issue. Again, probably fine to exclude.
1. `Expect-CT`: I'm not familiar with non-browser support for this header (e.g., `curl`) but nothing about it is inherent to browsers. I'd use it for an API.
1. `Referrer-Policy`: I'm not familiar with any non-browsers setting the `Referer` header, so it's probably okay to omit this, but it's worth researching.
1. `Strict-Transport-Security`: Similar to `Expect-CT`, in that nothing about it is inherent to browsers. I'd set it.
1. `X-Content-Type-Options`: Should only affect browsers, so it's probably okay to skip.
1. `X-DNS-Prefetch-Control`: Should only affect browsers, so it's probably okay to skip.
1. `X-Download-Options`: Only affects Internet Explorer 8, so it's probably okay to skip.
1. `X-Frame-Options`: I'd include it. See my note above.
1. `X-Permitted-Cross-Domain-Policies`: I'm not super familiar with how Adobe products fetch resources, but this doesn't seem specific to browsers and I'd set it.
1. `X-Powered-By`: not specific to browsers, so I'd omit the header as normal. (This offers basically no security benefit and is mostly for performance.)
1. `X-XSS-Protection`: Should only affect browsers, so it's probably okay to skip.

I'm hesitant to say "you're totally safe to remove this header" or "you should totally set this header" because every app is different, but those are my high-level thoughts.

Hope this helps! I'm going to close this issue but let me know if I should reopen.

**Comment by LJNeon** [comment]
Thanks for the quick and detailed response! No need to reopen, but I have one followup question if you don't mind. Are there any security headers I might consider using in a REST API that wouldn't be necessary in a webserver?

**Comment by EvanHahn** [comment]
None come to mind, but I'll let you know if I think of any.
