### ISSUE TITLE
requests not working when helmet is enabled!

### ISSUE THREAD

**Issue by Graham1384** [helmetjs/helmet#282]
here is my code to enable helmet.

`app.use(helmet({
  contentSecurityPolicy: false,
}));`

I have a post request for sending images using `/uploadImage`
when helmet is not enabled it works fine but when I enable it then the browser shows me my website's 404 error page

**Comment by EvanHahn** [comment]
This is happening because of something called Content Security Policy (also known as CSP), which Helmet sets by default. To solve your problem, you will need to configure Helmet's CSP.

[MDN has a good documentation about CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) which I would recommend reading for background. After that, take a look at [Helmet's README](https://github.com/helmetjs/helmet/) to see how to configure its CSP component.

You're probably seeing an error in your browser's console. You might be able to do something like this:

```js
app.use(
  helmet({
    contentSecurityPolicy: {
      directives: {
        ...helmet.contentSecurityPolicy.getDefaultDirectives(),
        "connect-src": ["'self'"],
      },
    },
  })
);
```

I'm going to close this issue because I don't think it's an issue with Helmet, but let me know if that's wrong and I will reopen.

**Comment by Graham1384** [comment]
I have to set CSP to false because if ebabled it won't let my website to load static css and js files
It will block them all
The problem is only with POST requests
it redirects me to my website's 404 error page

**Comment by EvanHahn** [comment]
What error(s) do you see?

**Comment by Graham1384** [comment]
unfortunately there is not any errors available.
my problem is similar to issue #93 
input uploads are disabled
I hope if there is a way to solve this issue

**Comment by Graham1384** [comment]
I noticed that the my image gets uploaded but after image upload page will automatically refresh.

this code will refresh the page:

`  res.redirect(req.get('referer'));
`
but when it runs it adds /undefined to header and shows 404 error page.
I think adding page URL will fix the issue

**Comment by Graham1384** [comment]
I changed it to 
`res.redirect('/myLink');`
and now everything works fine

is there any security problem with disabling CSP?

**Comment by EvanHahn** [comment]
Do you see errors in your browser console?

**Comment by Graham1384** [comment]
No

**Comment by Graham1384** [comment]
I have to disable 404 page to see if there is any errors
I'll let you know if there is any problem

Thank you for support

**Comment by EvanHahn** [comment]
> is there any security problem with disabling CSP?

Yes. CSP helps protect users who use modern browsers from common attacks like cross-site scripting (XSS).
