### ISSUE TITLE
Glitch using helmet on mern app and deploying it on heroku

### ISSUE THREAD

**Issue by olegs7771** [helmetjs/helmet#285]
Seems like after me  added helmet to my mern app and deployed to heroku . i see only blank screen..

**Comment by EvanHahn** [comment]
Do you see an error in your browser console?

**Comment by romanveriff** [comment]
@olegs7771, it could be `contentSecurityPolicy`.

see also
https://github.com/helmetjs/helmet#reference

**Comment by masbouj** [comment]
> Do you see an error in your browser console?

Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-LjklRjwKHMz4DntkPxFuyfhdeNizU+5hdZEhnuqfxEs='), or a nonce ('nonce-...') is required to enable inline execution.

Found this (https://medium.com/@szpytfire/create-react-app-refused-to-execute-inline-script-ea0301dea192) but its not working

**Comment by masbouj** [comment]
> @olegs7771, it could be `contentSecurityPolicy`.
> 
> see also
> https://github.com/helmetjs/helmet#reference

After some test, adding:
`app.use(
  helmet({
    contentSecurityPolicy: false,
  })
);`

Make it works

**Comment by EvanHahn** [comment]
This is likely happening because of something called Content Security Policy (also known as CSP), which Helmet sets by default. To solve your problem, you will need to configure Helmet's CSP.

[MDN has a good documentation about CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) which I would recommend reading for background. After that, take a look at [Helmet's README](https://github.com/helmetjs/helmet/) to see how to configure its CSP component.

You're probably seeing an error in your browser's console. You can use that to configure Helmet's CSP to avoid these issues.

You can also disable CSP, but this is less secure.

I'm going to close this issue because I don't think it's an issue with Helmet, but let me know if that's wrong and I will reopen.
