### ISSUE TITLE
Directives can only be added in kebab case

### ISSUE THREAD

**Issue by thomasdingemanse** [helmetjs/helmet#289]
When using the default directives as a starting point, it's not possible to specify other directives in camel case, only in kebab case. In other words, the following code works fine:

```js
const express = require('express')
const helmet = require('helmet')

const app = express()

const PORT = 3000

app.use(helmet.contentSecurityPolicy({
    directives: {
        ...helmet.contentSecurityPolicy.getDefaultDirectives(),
        'script-src': ["'self'", "example.com"]
    }
}))

app.get('/', (req, res) => {
    res.send('Hello World!')
})

app.listen(PORT, () => {
    console.log(`Example app listening at http://localhost:${PORT}`)
})
```

I've checked the `Content-Security-Policy` header, which correctly includes `script-src 'self' example.com;`. However, if I change `'script-src'` to `scriptSrc`, I get the following error:

```
            throw new Error(`Content-Security-Policy received a duplicate directive ${JSON.stringify(directiveName)}`);
            ^

Error: Content-Security-Policy received a duplicate directive "script-src"
```

While the workaround for this issue is easy (just use kebab case), it is inconsistent that these methods do not give the same result. I propose that either both methods throw an error or both just add the directive to the default directives (which is the preferred option in my opinion).

I'm using express **4.17.1**, helmet **4.3.1**, and node **14.15.1**.

**Comment by EvanHahn** [comment]
You're right that this is a little surprising.

First, to fix your problem in the short term. This is happening because `helmet.contentSecurityPolicy.getDefaultDirectives` returns an object in kebab case:

https://github.com/helmetjs/helmet/blob/77bf87b09039a24c3172bc2cc0a5a5b24804fd09/middlewares/content-security-policy/index.ts#L37-L54

You can fix this in a number of ways:

1. Use kebab case (as you mentioned)
1. Stop using `helmet.contentSecurityPolicy.getDefaultDirectives` and set the defaults yourself
1. Convert the keys of `helmet.contentSecurityPolicy.getDefaultDirectives` to camel case. Here's a sketch that uses Lodash:

   ```js
   const { mapKeys, camelCase } = require("lodash");

   // ...

   const camelCasedDefaultDirectives = mapKeys(
     helmet.contentSecurityPolicy.getDefaultDirectives(),
     (_value, key) => camelCase(key)
   );

   // ...

   app.use(
     helmet.contentSecurityPolicy({
       directives: {
         ...camelCasedDefaultDirectives,
         "script-src": ["'self'", "example.com"],
       },
     })
   );
   ```

In the long term, we could change Helmet in at least two ways to address this:

1. Require everyone to use kebab case and drop support for camel case. I don't love this because people _do_ use camel case, but that would solve the problem.
1. Replace `getDefaultDirectives()` with something that sets the defaults regardless of how you've written _your_ directives. Here's a sketch of what that could look like:

   ```js
   helmet.contentSecurityPolicy({
     useDefaults: true,
     directives: {
       "script-src": ["'self'", "example.com"],
     },
   })
   ```

   This would have to be disabled by default in Helmet 4, but I could make it on by default with a breaking change in Helmet 5 (or beyond).

There might be other options here, and I'd like to spend some time thinking about what's best before I make a decision.

**Comment by thomasdingemanse** [comment]
Thanks for your detailed reply! I also prefer the second option you mentioned. Another (non-breaking!) option might be to check for both camel case and kebab case directives when parsing the options, recognize them as the same directive, and merge them if they occur in both forms (or throw an error if they are both different from the default). Then it doesn't really matter if `getDefaultDirectives()` uses camel case or kebab case.

I must admit that I'm not entirely sure if this would work in practice, but I'd like to do some more digging to see if this could work. If you agree that this is a good way to approach the issue, of course!

**Comment by EvanHahn** [comment]
I currently prohibit that (as you're seeing) because it's unclear what the behavior should be.

For example, let's say you provide the following two keys:

```js
scriptSrc: ["'none'"],
"script-src": ["'self'", "example.com"],
```

I think there are four possible options in this case:

1. Combine them into `'none' 'self' example.com`. This is invalid, but is straightforward. It also seems like it _might_ be a mistake, so maybe we log a warning.
1. First one wins; the result would be `'none'`. The second is ignored, possibly with a warning.
1. Last one wins; the result would be `'self' example.com`. The first is ignored, and we might log a warning.
1. Prohibit this and throw an error. This is what Helmet does today.

Personally, I think the last option is the least surprising.

We _could_ try to do something where we allow duplicates if the first value is from `getDefaultDirectives()`. For example, we could ignore duplicates if the value matches the default. But there are many edge cases where, at least to me, the behavior would be surprising.

I think a `useDefaults` option (or equivalent) feels like the right move, but I'd still want to think on it some more.

**Comment by thomasdingemanse** [comment]
You make a good point. I agree that option 4 makes the most sense and that a `useDefaults` setting which is disabled by default in helmet 4 and enabled by default in version 5 seems to be the most intuitive.

**Comment by awentzel** [comment]
I struggled with this issue for a long time today trying to implement `frame-ancestors` as documentation uses a mix of both methods but didn't ever explain this nuanced issue. I thumbed up my preference.

**Comment by EvanHahn** [comment]
I'm planning to add a new option, `useDefaults`, which overrides the defaults. This should be used instead of `helmet.contentSecurityPolicy.getDefaultDirectives()`. It's `false` by default to preserve backwards compatibility, but will become `true` in `helmet@5`.

You can see the upcoming change in #299. Feedback welcome!

**Comment by EvanHahn** [comment]
Planning on adding a `useDefaults` option in v4.6.0. Follow along with this change in #301.

When that PR is merged, I'll close this issue and open a new one to make `useDefaults` `true` by default.

**Comment by EvanHahn** [comment]
The `useDefaults` option was added to `helmet@4.6.0` and `helmet-csp@3.4.0`.

The option defaults to `false`, but that will change to `true` in the next major version. You can see that work tracked in #314 and follow along with all of Helmet v5 in #309. (Help is wanted on a number of these issues!)
