### ISSUE TITLE
Strict-Transport-Security header should not be sent over HTTP

### ISSUE THREAD

**Issue by JBYoshi** [helmetjs/helmet#290]
According to [RFC 6797](https://tools.ietf.org/html/rfc6797#section-7.2):

> An HSTS Host MUST NOT include the STS header field in HTTP responses conveyed over non-secure transport.

Helmet always sends this header, regardless of the transport. Would it be possible to disable it on non-HTTPS connections?

**Comment by EvanHahn** [comment]
This is a good question.

Older versions of this middleware respected this part of the RFC, but that was [removed](https://github.com/helmetjs/helmet/issues/232) because Helmet can't detect HTTPS reliably.

Express sets `req.secure` to `true` if the incoming request uses HTTPS. But this isn't reliable for two reasons:

1. Helmet doesn't require you to use Express. In theory, you could use it with Node's native HTTP module. This has long been a design goal. Happy to expand on this, but that means that `req. secure` may be undefined.
2. `req.secure` may get the wrong answer in some cases, depending on proxy settings.

So what should Helmet do?

There's this line describing what browsers should do with the header:

> If an HTTP response is received over insecure transport, the UA MUST ignore any present STS header field(s).

In other words: while it's a mistake to send the header over insecure HTTP, it's harmless (other than wasted bandwidth).

That means Helmet has three options:

1. Always set the header, which might be a harmless mistake in some cases. This is what Helmet does today.
2. Conditionally set the header, which requires the condition to be correct (using `req.secure` or some user-configurable option). This is what Helmet did in prior versions.
3. Give up and never set the header at all. This doesn't really feel like an option, but I wanted to point it out.

Helmet tries to be a "set and forget" module. Though it's configurable, most users shouldn't need to mess with it to get security benefits. That's why we go with the first option: always set the header.

If you really want to set the header conditionally, you totally can. Here's how I'd do it:

```js
app.use(
  helmet({
    hsts: false,
  })
);

const hstsMiddleware = helmet.hsts();
app.use((req, res, next) => {
  if (req.secure) {
    hstsMiddleware(req, res, next);
  } else {
    next();
  }
});
```

I'm going to close this issue because I don't think anything needs to change in Helmet. Hope this response helps!
