### ISSUE TITLE
Can Helmet be Used in middleware?

### ISSUE THREAD

**Issue by madsteer** [helmetjs/helmet#294]
I'm using a software module that someone else wrote.  It builds an express server with certain security configurations and then returns that server and a couple of middleware functions that can be used with routes on the server by a consuming app.  So the 'security-express-server' module that I'm using has something like
```
function setupServer() {
  const server = express()
  server.use(helmet())
 return server
}
```
Then the consuming app can
```
const securitySetup = require('security-express-server')
. . .
const { server, authMiddleware } = securitySetup({ options })
const { uiAuthMiddleware, apiAuthMiddleware } = authMiddleware
. . .
server.use('/api', apiAuthMiddleware, async (req, res) => {
. . .
}
```
when the security-express-server module bumped it's helmet dependency from version 3.* to 4.*, the `server.use(helmet())` line broke my app because I needed a different CSP than what helmet provides by default.  At first I figured this module should be configured to use `server.use(helmet({ contentSecurityPolicy: false }))` instead, but then I wondered how that would affect the consuming app of this module.  Can helmet be "used" twice (two `server.use(helmet())` statements)?  Once in the module providing the express server and some middleware, and again in the app consuming said server and middleware?  If so, can the consuming app override the `contentSecurityPolicy: false` configuration of the module providing the express server?  Or, could the consuming app not use helmet but still have a CSP policy in an http meta tag or other?

Looking for advice on how the security-express-server should be configured.  Should it be using helmet at all (or leave it to the consuming apps to decide), and if it can be used can the CSP be turned off in the module while still allowing the consuming app to turn back on?  Thanks,

**Comment by EvanHahn** [comment]
I don't know the details about security-express-server, but my first instinct would be to see if it lets you configure Helmet at all.

However, if you can't do that (or don't want to for some reason), including Helmet twice is usually okay. If a part of Helmet wants to set a header (say, `Content-Security-Policy`), it will do so, ignoring the previous header value.

For example, in this code snippet:

```js
const app = express();

app.use(helmet());

app.use(
  helmet({
    contentSecurityPolicy: {
      directives: {
        "default-src": "'none'",
      },
    },
  })
);
```

The first call to `helmet()` is run, but all of the header values are overridden by the next one. However, doing something like this will use the first `Content-Security-Policy` header value; it won't be removed.

```js
app.use(helmet());

app.use(helmet({ contentSecurityPolicy: false }));
```

I hope that answers your question. I'm going to close this issue because I don't think this is a problem with Helmet specifically, but (1) I'm happy to reopen if that's wrong (2) I'm happy to continue discussion here.
