### ISSUE TITLE
Unable to stop clickjacking

### ISSUE THREAD

**Issue by arinhere** [helmetjs/helmet#311]
Hi,

I added all the required attributes for helmet. But it seems clickjacking still happening. 

Additional info: my application is running from subdomain. So something like 'https://xyz.example.com'

Can any of you help on this. The following is my configuration

 app.use(
        helmet.noSniff(),
        helmet.dnsPrefetchControl(),
        helmet.ieNoOpen(),
        helmet.referrerPolicy(),
        helmet.xssFilter(),
        helmet.hsts({
            // Strict-Transport-Security
            maxAge: 63072000, // Time in seconds
            preload: true,
            includeSubDomains: true
        }),
        helmet.contentSecurityPolicy({
            directives: {
                defaultSrc: ["'none'"],
                scriptSrc: ["'self'", "'unsafe-inline'", "'report-sample'"],
                reportUri: '/report-violation',
                objectSrc: ["'none'"],
                upgradeInsecureRequests: true,
                workerSrc: false,
                frameAncestors: ["'none'"]
            }
        })
    );
    app.use(frameguard({ action: 'deny' }));
    app.disable('x-powered-by');
    app.use(nocache());
    app.use(cors());
    app.use(compression());

I am getting the following in response header. 

access-control-allow-headers: Content-Type, Origin, X-Amz-Date, Authorization, X-Api-Key, X-Amz-Security-Token, Access-Control-Allow-Headers, X-Requested-With, Access-Control-Allow-Origin
access-control-allow-methods: GET, POST, OPTIONS, PUT, PATCH, DELETE
access-control-allow-origin: *
cache-control: no-store, no-cache, must-revalidate, proxy-revalidate
Connection: keep-alive
content-encoding: gzip
content-security-policy: default-src 'none'; script-src 'self' 'unsafe-inline' 'report-sample'; report-uri /report-violation; object-src 'none'; upgrade-insecure-requests; frame-ancestors 'none'
content-type: application/json; charset=utf-8
date: Thu, 29 Apr 2021 09:27:41 GMT
etag: W/"192b-lXcL453LzPsFm2K5uEezNzLqVZg"
expect-ct: max-age=0
expires: 0
pragma: no-cache
referrer-policy: no-referrer
strict-transport-security: max-age=63072000; includeSubDomains; preload
surrogate-control: no-store
transfer-encoding: chunked
vary: Accept-Encoding
x-content-type-options: nosniff
x-dns-prefetch-control: off
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-xss-protection: 1; mode=block

Please let me know

Thanks

**Comment by EvanHahn** [comment]
Could you elaborate? What kind of problem are you seeing? How is the clickjacking happening?

**Comment by arinhere** [comment]
Thanks for replying so fast.

I implemented the above in my nodejs API config and run my application. Then I created a sample HTML and included the application URL in that iframe and its loaded.

<html>
    <head>
        <title>Clickjack test page</title>
    </head>
    <body>
        <iframe src="**http://******.localhost:4400/**" width="500" height="500"></iframe>
    </body>
</html>

and it's loaded the content ... where as it should not

**Comment by EvanHahn** [comment]
I'm not sure what's happening here, but I have a few thoughts.

1. Are you sure that you're getting those headers from the iframe? If not, why not?
2. Does it happen when the outer page is a "real" web server instead of a page served with the `file://` protocol?
3. Do you get any relevant errors or warnings in your browser console?
4. Could you create a minimal app that reproduces this issue?

**Comment by swapnil0545** [comment]
Hi @EvanHahn ,
1. Yes
2. Yes
3. No
4. Heres the actual link for the iframe 
https://jsfiddle.net/hv70wqz5/1/ you can see any XHR response headers for all the above implemented things mentioned by @arinhere

**Comment by EvanHahn** [comment]
In that fiddle, you're putting `https://cranial-qa.xeniohealth.com/` into an iframe. That page isn't served with a `Content-Security-Policy` or `X-Frame-Options` header, so it's allowed to be put into an iframe. It doesn't matter what headers are set on the _outer_ page. 

I made [a test app](https://github.com/EvanHahn/helmet-issue-311) to help demonstrate how this works.

I don't think this is an issue with Helmet so I'm going to close, but I'm happy to continue to help you debug.

**Comment by arinhere** [comment]
Hi @EvanHahn,

Thanks for your quick response on the issue. 

Let me put the question a little differently. Please check this fiddle
https://jsfiddle.net/arinhere/ehf6skn4/1/

I used linkedin URL here and its showing desired results. 

So my question is, is there anyway we can acheive this using helmet?

please let me know.

Thanks in advance.

**Comment by EvanHahn** [comment]
## The short answer

To prevent _other websites_ from loading _your_ website in an iframe:

1. Set the `X-Frame-Options` header, like this:
   ```js
   app.use(frameguard({ action: 'deny' }));
   ```

2. Set the `Content-Security-Policy` header with the `frame-ancestors` directive set to `'none'`, like this:
   ```js
   helmet.contentSecurityPolicy({
     directives: {
       // ...
       frameAncestors: ["'none'"],
     },
   });
   ```

To prevent _your_ website from loading any iframes, set the `frame-src` directive to `'none'`, like this:

```js
helmet.contentSecurityPolicy({
  directives: {
    // ...
    frameSrc: ["'none'"],
  },
});
```

## The long answer

I think there may be some confusion about how these headers work, and what the vulnerabilities are.

There are two HTTP response headers that basically do the same thing:

1. [`X-Frame-Options`][xfo] is a legacy header that effectively lets you say, "don't put me in an iframe!"
2. [`Content-Security-Policy`][csp] is a newer header that does many different things. One of them is [the `frame-ancestors` directive][fa], which also lets you say, "don't put me in an iframe!"

Helmet helps you set both of these headers.

When your browser loads any iframe, it checks for these headers before showing it to the user. If the page being put in the frame (the _inner_ page, not the _outer_ page) says "don't put me in an iframe", then the browser won't show that iframe. If those headers are missing or permit loading in an iframe, the browser _will_ show the iframe.

The key point here: the browser checks for these HTTP headers on the _inner_ page (i.e., the page _inside_ the iframe), not the _outer_ page.

`linkedin.com/feed/` sets `X-Frame-Options: sameorigin`. In other words, it's saying, "don't put me in an iframe!" So this won't ever load:

```html
<!-- This won't work. LinkedIn says "don't put me in an iframe" -->
<iframe src="https://linkedin.com/feed/" />
```

It _does not matter_ what HTTP headers you use on the outer page—you will never be able to load `linkedin.com/feed/` in an iframe.

In contrast, `cranial-qa.xeniohealth.com` does _not_ set either of these headers. That means that trying to load it in an iframe will work. In other words, this will load the page just fine:

```html
<!-- This will work, because the site doesn't say anything about whether it can be in an iframe -->
<iframe src="https://cranial-qa.xeniohealth.com/" />
```

If you're trying to protect yourself from clickjacking attacks, you'll want to set both of these headers.

You may be looking for [the `frame-src` Content Security Policy directive][fs]. This directive applies to the _outer_ page. Instead of prohibiting _yourself_ from being put into an iframe, you can prohibit iframes from loading on your page. For example, with this directive:

    frame-src https://foo.example.com

You could load an iframe at `https://foo.example.com`, but not `https://bar.example.com`.

You can also do this, to prohibit _any_ iframes from loading:

    frame-src 'none'

Here's how you might set that with Helmet:

```js
helmet.contentSecurityPolicy({
  directives: {
    // ...
    frameSrc: ["'none'"],
  },
});
```

[xfo]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options
[csp]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy
[fa]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors
[fs]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-src
