### ISSUE TITLE
frameguard with Content Security Policy frame-ancestors?

### ISSUE THREAD

**Issue by louy2** [helmetjs/helmet#323]
From [RFC7034](https://datatracker.ietf.org/doc/html/rfc7034#section-2.3.2.2):

> A revised version of X-Frame-Options in the form of a Frame-Options directive in CSP 1.1 [CSP-1-1] will unify the behavior, and it is expected that newer implementations will use it rather than the mechanisms documented here.

[The latest documentation of CSP frame-ancestors](https://www.w3.org/TR/CSP2/#directive-frame-ancestors)

It seems this directive is implemented across major browsers from the implementation report.

**Comment by EvanHahn** [comment]
`frameguard` calls this out in its documentation:

> This header is superseded by the `frame-ancestors` Content Security Policy directive but is still useful on old browsers.

I don't think I'm going to change the way the middleware works, but I _do_ want to document the CSP directive as a preferred alternative.

I'm going to close this issue because I don't plan to make any changes here, but let me know if that's wrong (or if you don't like the way I've done it) and I'm happy to reopen.

**Comment by louy2** [comment]
I created the issue before I learned about `helmet.contentSecurityPolicy` so now I see what you intend.
