### ISSUE TITLE
Question on correctly setting 'frame-ancestors'

### ISSUE THREAD

**Issue by MagRelo** [helmetjs/helmet#331]
Hi, great project! I'm having trouble allowing my site to be embedded via an iFrame.

My Helmet config:

```app.use(
  helmet.contentSecurityPolicy({
    directives: {
      ...helmet.contentSecurityPolicy.getDefaultDirectives(),
      'img-src': ["'self'", 'https:', 'data:'],
      'frame-src': ["'self'", 'auth.magic.link'],
      'frame-ancestors': [
        "'self'",
        'https://codepen.io/',
        'https://game.thenemesis.io',
      ],
      'connect-src': [
        "'self'",
        'rinkeby-api.opensea.io',
        'api.opensea.io',
        'ws:',
        '*.walletconnect.org',
        'wss://*.walletconnect.org:443',
        'wss://*.rara.social:443',
        '*.infura.io',
        '*.sentry.io',
      ],
      'media-src': ["'self'", '*', '*.opensea.io'],
      'worker-src': ["'self'", 'blob:'],
    },
  })
);
```

Here is a codepen I'm using to test: https://codepen.io/magrelo/pen/XWgXNxo

In the console I'm getting this error : 

`"Refused to frame 'https://v1.rara.social/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self' https://codepen.io/ https://game.thenemesis.io".`

I've tried a few variations on how I list the domain in the 'frame-ancestors' config, ie, no protocol, wildcards, etc, but I'm always getting the same error so I assume I'm listing them incorrectly(?)

thanks in advance!

**Comment by EvanHahn** [comment]
Spent a few minutes looking into this. Here are two thoughts:

1. Codepen puts your pen into an iframe of its own, not hosted on `codepen.io`. If you open your browser's developer tools and poke around, you'll see that it's inside `cdpn.io`. Maybe try adding `cdpn.io` instead of `codepen.io`?
2. You might run into _another_ issue where the `X-Frame-Options` header is set to `SAMEORIGIN`. I don't know if that'll cause issues for you (I don't remember off the top of my head), but if it does, you'll want to disable Helmet's `frameguard` middleware or whatever you're using to set that header.

Hope this helps!
