### ISSUE TITLE
Outdated referrer-policy fallback

### ISSUE THREAD

**Issue by sauravhiremath** [helmetjs/helmet#333]
The referrer-policy fallback is `no-referrer` in the helmet project ([codebase-link](https://github.com/helmetjs/helmet/blob/main/middlewares/referrer-policy/index.ts#L20)).
But the latest docs have updated the fallback to `strict-origin-when-cross-origin`.

Source - https://w3c.github.io/webappsec-referrer-policy/#default-referrer-policy

**Comment by EvanHahn** [comment]
I'll take a look at this. It's probably a breaking change, too, so we should keep that in mind.

**Comment by EvanHahn** [comment]
I took a look at this, and I don't think we want to do this.

Helmet's defaults aren't necessarily the defaults in the spec. `no-referrer` preserves privacy a bit better than `strict-origin-when-cross-origin`, which is why I selected it for Helmet's default. In other words, it doesn't matter what the spec says.

Does that make sense? What do you think?

**Comment by EvanHahn** [comment]
I'm going to close this issue because I don't think there's more to do here. Let me know if that's wrong and I'm happy to reopen.
