### ISSUE TITLE
Helmet - CSS don't load

### ISSUE THREAD

**Issue by LHCLYT** [helmetjs/helmet#356]
Hey, when using helmet, all the CSS and resources on my site stop loading, how can I fix that?

**Comment by EvanHahn** [comment]
This is likely happening because of something called Content Security Policy, which Helmet sets by default. To solve your problem, you will need to configure Helmet's CSP.

[MDN has a good documentation about CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) which I would recommend reading for background. After that, take a look at Helmet's README to see how to configure its CSP component.

If you open your browser's developer tools, you're probably seeing an error like this:

```
Content Security Policy: This page's settings blocked the loading of a resource at inline ("style-src").
```

This error is telling you that the `style-src` directive of your CSP does not allow whatever CSS you're trying to load, and so it was blocked.

I'm going to close this issue because I believe this has been resolved (and not an issue with Helmet directly). Feel free to comment further with error messages you see, and I can help out.
