### ISSUE TITLE
Redundant `exports` assignment?

### ISSUE THREAD

**Issue by Fdawgs** [helmetjs/helmet#377]
As the title states, there appears to be a redundant `exports` assignment:

https://github.com/helmetjs/helmet/blob/b99131e28fd194f5a31873da1c3252c602fe5c74/index.ts#L277-L278

According to https://nodejs.org/api/modules.html#exports-shortcut, `exports` "is assigned the value of `module.exports` before the module is evaluated". Since there is a `module.exports` immediately following it i'm not sure `exports` is needed?

**Comment by EvanHahn** [comment]
I did this because I wanted to support CommonJS imports and ESM imports, and this was the only way I could get it to work at the time. It's possible (likely) that this has changed. I would love to make it simpler if I can support both.

I want to drop CommonJS support one day, but for a package like Helmet (that most people install and forget about), I want to minimize user effort.

**Comment by Fdawgs** [comment]
Gotcha, thanks Evan!
