### ISSUE TITLE
CrossOriginResourcePolicyOptions: why not union type for policy?

### ISSUE THREAD

**Issue by gurdiga** [helmetjs/helmet#379]
Hi! 👋🙂

The [MDN docs][0] for `Cross-Origin-Resource-Policy` say that it can have one of 3 values: `same-site | same-origin | cross-origin` — which looks a lot like a union type by the way… 😉

[0]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Resource-Policy

…and, I just wanted to ask if there is a reason for having [the `policy` member in `CrossOriginResourcePolicyOptions`][1] is of type `string` instead of a union type like this:

[1]: https://github.com/helmetjs/helmet/blob/485d6b6/middlewares/cross-origin-resource-policy/index.ts#L4

```ts
export interface CrossOriginResourcePolicyOptions {
  policy?: "same-site" | "same-origin" | "cross-origin";
}
```

Cheers!

**Comment by EvanHahn** [comment]
This is done in the next version of Helmet, v6. The code looks almost exactly like you're suggesting:

https://github.com/helmetjs/helmet/blob/931a4fb0547ad2a046d5e65c16c36d5b737840a2/middlewares/cross-origin-resource-policy/index.ts#L3-L5

See #370 for more.

I'm going to close this because I think this answers your question, but let me know if that's wrong and I can reopen.
