### ISSUE TITLE
error is always undefined

### ISSUE THREAD

**Issue by singh-inder** [helmetjs/helmet#471]
Hi, below code always throws an CORS exception as expected, but the err value is always undefined. I also tried to catch error in express global error handler, didn't work either. Is this the wrong way to catch errors?

```ts
app.use((req, res, next) => {
  const middleware = helmet();

  middleware(req, res, err => {
    console.log(err); // undefined
    next(err);
  });
});
```

**Comment by EvanHahn** [comment]
Your code looks correct.

Helmet very rarely has errors this way, though it can sometimes happen if you've made a mistake. In other words, it should almost always be `undefined`.

Helmet has this signature because it's the common pattern for Express middleware, which is the primary use case.

Does that answer your question?

**Comment by singh-inder** [comment]
yes, thank you for your time.
