### ISSUE TITLE
The road to 1.0

### ISSUE THREAD

**Issue by EvanHahn** [helmetjs/helmet#92]
Helmet is split up into many repos, so the to-do list is here instead of in individual issues. I am sorry.

- [x] Mission statement: Helmet is just for HTTP headers. This means rewording some of the readme and removing the `crossdomain` middleware.
- [ ] Completely remove `crossdomain` middleware—it's just deprecated right now.
- [ ] Test app for CSP, independent of Helmet. The CSP module does a lot of user-agent sniffing but that's all guesswork; I'd love a way to test browsers' CSP support. See discussion in [CSP issue 10](https://github.com/helmetjs/csp/issues/10).
- [x] [CSP level 2](https://github.com/helmetjs/csp/issues/9)

I'd love discussion/feedback on this roadmap.

**Comment by evilpacket** [comment]
+1 to Mission Statement so that we don't necessarily have to keep clarifying about feature requests
+1 for CSP level 2
+1 for docs

**Comment by devlo** [comment]
You should add performance optimizations.
This is with CSP on:

```Concurrency Level:      1000
Time taken for tests:   19.060 seconds
Complete requests:      20000```

This is with CSP off:

```Concurrency Level:      1000
Time taken for tests:   15.827 seconds
Complete requests:      20000```

**Comment by EvanHahn** [comment]
@devlo The CSP module is pretty slow because it has to parse incoming useragents, which takes time. Any thoughts on how to make this faster?

**Comment by KevinMartin** [comment]
Instead of parsing every single request's UA, you could save the last 20, 50, 100, etc... in memory and check it before parsing it. I noticed you also did `parseFloat` on the version numbers a lot. I would move that to the function that parses the UA that way on a cache hit, the version number is already floated and you can skip it the next time around.

**Comment by KevinMartin** [comment]
Btw, it would be great if you can extract this into a standalone lib, instead of it being Express specific/targeted.

I use Koa and I have to depend on koa-helmet which:
 1. seems to be outdated
 2. doesn't suit my needs.

A standalone library would allow me to do whatever I want, such as create my own custom middleware that will handle a certain CSP policy for one path and another CSP policy for a different path... or a dynamic CSP policy depending on a request input...

**Comment by EvanHahn** [comment]
@KevinMartin The current `csp` middleware has to parse the useragent and then decide on one or more headers to set. While these things could be separated into a separate module, they feel _really_ closely tied to the request and response.

Thoughts on this?

**Comment by devlo** [comment]
Did you try native node.js addons written in C/C++ that do the same thing ? 
You should check if context switching between JS and C/C++ is worth it.
Another solution is using https://github.com/3rd-Eden/useragent
 which has function allowing in-memory caching

**Comment by KevinMartin** [comment]
@EvanHahn,

A standalone lib could still parse the UA and return an object of the headers to set:

```js
// Sample Koa App
var app = require('koa')(),
    csp = require('helmet-csp-core'),
    policy = csp({ ... });

app.use(function *(next) {
    var header,
        headers = policy(this.get('user-agent'));

    for (header in headers) {
        this.set(header, headers[header]);
    }

    yield next;
});
```

Another Pro for this would be that other modules/frameworks could then use `helmet-csp-core` as a dependency...

The other thing I could suggest is instead of a separate module, to just add a separation of duties within the current module:

```js
// helmet-csp module
function csp(options) {
    return function policy(ua) { ... };
}

module.exports = csp;

module.exports.express = function expressMiddleware(options) {
    var policy = csp(options);
    return function (req, res, next) { ... };
};

module.exports.koa = function koaMiddleware(options) {
    var policy = csp(options);
    return function *(next) { ... };
};

// my-app.js
var app = require('express')(),
    csp = require('helmet-csp');

app.use(csp.express({ ... }));
```

**Comment by KevinMartin** [comment]
I really like all of the helmet modules, but the fact that they are targeted solely for Express, is a killer, since i either use Koa or custom frameworks.

**Comment by EvanHahn** [comment]
@KevinMartin Let's take this to #100.

**Comment by venables** [comment]
I think we should just call it and name the existing code a 1.0.0 release. It's being used in production (fairly widely, as far as i can tell), so it really shouldn't be a 0.x release.  We could have this other proposed work (modified docs, mission statement, csp update) as part of a patch (or potentially, a major) release.

**Comment by EvanHahn** [comment]
@venables I'm hesitant to do so—the CSP module feels really brittle at the moment and needs support for Level 2 which will likely break its API. I'm planning on bumping to `helmet@1.0.0` once that's done, but it's a big effort I haven't had time for at the moment.

**Comment by EvanHahn** [comment]
CSP level 2 is finally added in `helmet@0.11.0` and `helmet-csp@0.3.0`!

**Comment by EvanHahn** [comment]
Closing this—1.0.0 is out!
